version: '3'
services:
  foundryvtt:
    image: direckthit/fvtt-docker:latest
    container_name: fvtt
    ports: 
      - 30005:30005
    volumes:
      - /path/to/your/foundry/data/directory:/data/foundryvtt
      - /path/to/your/foundry/zip/file:/host
    restart: unless-stopped
